# LLM Configuration
llm:
  model: "mistral"
  temperature: 0.7
  context_window: 4096
  top_p: 0.9
  top_k: 40

# Memory System Configuration
memory:
  vector_db_path: "./data/vector_db"
  embedding_model: "all-MiniLM-L6-v2"
  max_memories: 1000

# Agent Configuration
agents:
  email:
    enabled: true
    check_interval: 300  # seconds
    max_emails: 100
    
  document:
    enabled: true
    watch_directories:
      - "/mnt/nas/documents"
      - "./data/documents"
    supported_formats:
      - "pdf"
      - "docx"
      - "txt"
    
  social_media:
    enabled: true
    platforms:
      - "twitter"
      - "facebook"
    update_interval: 600  # seconds

# Integration Configuration
integrations:
  nas:
    type: "smb"
    host: "nas.local"
    share: "documents"
    mount_point: "/mnt/nas"
    
  email:
    type: "imap"
    server: "imap.gmail.com"
    port: 993
    use_ssl: true
    
  social_media:
    twitter:
      api_key: "${TWITTER_API_KEY}"
      api_secret: "${TWITTER_API_SECRET}"
    facebook:
      app_id: "${FACEBOOK_APP_ID}"
      app_secret: "${FACEBOOK_APP_SECRET}"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"

# Logging Configuration
logging:
  level: "INFO"
  file: "./logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Security Configuration
security:
  api_key_required: true
  encryption_key_path: "./config/encryption.key"
  ssl_enabled: false
  ssl_cert_path: "./config/ssl/cert.pem"
  ssl_key_path: "./config/ssl/key.pem" 